import {useEffect,useState} from 'react'
import {Activity,ArrowRight,FlaskConical,Sparkles} from 'lucide-react'
import {api,Opportunity} from './api'
import {money} from './format'

export default function AdvancedLab(){
 const [opp,setOpp]=useState<Opportunity|null>(null),[data,setData]=useState<any>(null),[stress,setStress]=useState<any>(null),[intel,setIntel]=useState<any>(null)
 const [amount,setAmount]=useState(800000),[hours,setHours]=useState(12),[busy,setBusy]=useState(''),[error,setError]=useState('')
 useEffect(()=>{void Promise.all([api.opportunities(),api.intelligence()]).then(([items,market])=>{setOpp([...items].reverse().find(x=>x.match)||null);setIntel(market)}).catch(e=>setError(String(e)))},[])
 const run=async(kind:string)=>{if(!opp)return;setBusy(kind);setError('');try{if(kind==='twin')setData(await api.marketTwin(opp.id,{minimum_amount:amount,max_settlement_hours:hours,market_regime:'STRESSED'}));if(kind==='strategy')setData(await api.strategy({opportunity_id:opp.id,minimum_amount:amount,max_settlement_hours:hours}));if(kind==='stress')setStress(await api.stress(opp.id))}catch(e){setError(e instanceof Error?e.message:'Simulation failed')}finally{setBusy('')}}
 return <main><header><div><p className="eyebrow">PURE COUNTERFACTUAL SANDBOX • DEMO ONLY</p><h1>Market Digital <em>Twin.</em></h1><p className="lede">Clone current marketplace state, explore supplier terms, and test network shocks without mutating persisted state.</p></div></header>{error&&<div className="error-banner">{error}</div>}
 {!opp?<section className="empty-market"><FlaskConical/><div><h2>Run a market first.</h2><p>The lab needs a completed opportunity to clone.</p></div></section>:<><section className="lab-controls"><label>Minimum capital<strong>{money(amount)}</strong><input type="range" min="500000" max={opp.invoice.amount} step="50000" value={amount} onChange={e=>setAmount(+e.target.value)}/></label><label>Settlement ceiling<strong>{hours}h</strong><input type="range" min="12" max="96" step="12" value={hours} onChange={e=>setHours(+e.target.value)}/></label></section><div className="lab-actions"><button className="primary" onClick={()=>run('twin')}>{busy==='twin'?<Activity className="spin"/>:<Sparkles/>} Stressed twin</button><button onClick={()=>run('strategy')}>Strategy curve</button><button onClick={()=>run('stress')}>Stress Lab</button></div>
 {data?.baseline&&<section className="twin-compare"><article><small>BASELINE</small><h2>{data.baseline.winner_name||'No winner'}</h2><b>{data.baseline.winner_score}/100</b></article><ArrowRight/><article><small>SIMULATED</small><h2>{data.simulated.winner_name||'No winner'}</h2><b>{data.simulated.winner_score}/100</b></article><div>{data.explanations.map((x:string)=><p key={x}>• {x}</p>)}<small>{data.notice}</small></div></section>}
 {data?.trade_off_curve&&<Table title="SUPPLIER STRATEGY" rows={data.trade_off_curve.map((x:any)=>[`${x.settlement_hours}h`,`${x.eligible_providers} viable`,x.average_rate?`${x.average_rate}%`:'—',x.winner_name||'No winner'])} note={data.recommendation_text}/>} {stress&&<Table title={`STRESS LAB • ${stress.resilience_score}/100`} rows={stress.scenarios.map((x:any)=>[x.scenario,`${x.eligible_providers} viable`,x.average_rate?`${x.average_rate}%`:'—',x.winner||'MARKET FAILURE'])} note={stress.notice}/>} {intel&&<section className="metrics"><article><small>MARKET HEALTH</small><strong>{intel.market_health}</strong><p>Current-state heuristic</p></article><article><small>UTILIZATION</small><strong>{intel.capital_utilization}%</strong><p>Exposure / capacity</p></article><article><small>COMPETITION</small><strong>{intel.competition_index}</strong><p>Eligible-provider ratio</p></article><article><small>TOP LIQUIDITY</small><strong>{intel.top_provider_liquidity_share}%</strong><p>Current PRATIN state</p></article></section>}</>}</main>
}
function Table({title,rows,note}:{title:string;rows:string[][];note:string}){return <section className="lab-table"><h2>{title}</h2>{rows.map(row=><div key={row[0]}>{row.map((x,i)=>i===0?<b key={x}>{x}</b>:<span key={x}>{x}</span>)}</div>)}<p>{note}</p></section>}
