export type Offer={id:string;provider_id:string;provider_name:string;provider_type:string;status:'OFFER'|'DECLINE';annual_rate:number|null;financed_amount:number|null;fees:number|null;settlement_hours:number|null;total_effective_cost:number|null;reasons:string[]}
export type RankedOffer={offer:Offer;eligible:boolean;suitability_score:number;hard_constraint_failures:string[];rank:number|null}
export type RiskFactor={label:string;impact:'positive'|'negative'|'neutral';points:number;explanation:string;reason_code?:string}
export type VerificationResult={status:string;confidence:number;verified_fields:string[];uncertain_fields:string[];reasons:string[];reason_codes?:string[];simulation_notice?:string}
export type RiskAssessment={score:number;band:string;confidence:number;factors:RiskFactor[];missing_information:string[];policy_version:string}
export type RiskLedgerEntry={id:string;opportunity_id:string|null;invoice_number:string;supplier_name:string;buyer_name:string;amount:number;evaluated_at:string;verification:VerificationResult;risk:RiskAssessment;provenance:'SERVICE'|'FIXTURE'}
export type Opportunity={id:string;status:string;invoice:{invoice_number:string;supplier_name:string;buyer_name:string;amount:number};requirements:{minimum_amount:number;max_settlement_hours:number;desired_tenor_days:number};evaluation?:{verification:VerificationResult;risk:RiskAssessment};match?:{recommended_offer_id:string|null;ranked_offers:RankedOffer[];recommendation_reasons:string[]};integration_status:Record<string,string>}
export type Metrics={available_liquidity:number;active_opportunities:number;offers_generated:number;financing_allocated:number;settlements:number;provider_participation_rate:number}
const base=import.meta.env.VITE_API_BASE_URL||'http://127.0.0.1:8000'
async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(base+path,{headers:{'Content-Type':'application/json'},...init});if(!response.ok)throw new Error((await response.json()).detail||`Request failed: ${response.status}`);return response.json()}
export const api={scenarios:()=>request<Record<string,unknown>>('/api/scenarios'),reset:()=>request('/api/demo/reset',{method:'POST'}),create:(body:unknown)=>request<Opportunity>('/api/opportunities',{method:'POST',body:JSON.stringify(body)}),run:(id:string)=>request<Opportunity>(`/api/opportunities/${id}/run-market`,{method:'POST'}),settle:(id:string,offerId:string)=>request(`/api/opportunities/${id}/accept/${offerId}`,{method:'POST'}),metrics:()=>request<Metrics>('/api/platform/metrics'),riskLedger:()=>request<RiskLedgerEntry[]>('/api/risk-ledger'),riskLedgerEntry:(id:string)=>request<RiskLedgerEntry>(`/api/risk-ledger/${id}`)}
